package com.philipcutting.localweather

import com.philipcutting.localweather.networking.OneCallWeatherItem
import com.squareup.moshi.JsonAdapter
import com.squareup.moshi.Moshi
import org.junit.Assert
import org.junit.Test

class NetworkOneCallAllUnitTests {




    @Test
    fun `test url returns code 200 with given string`() {
        val moshi = Moshi.Builder().build()
        val adapter : JsonAdapter<OneCallWeatherItem> = moshi.adapter(OneCallWeatherItem::class.java)
        val weatherData = adapter.fromJson(testLocalJsonDataLong())


        Assert.assertEquals(801, weatherData?.currentWeather?.weather?.first()?.id)
    }

}


private fun testLocalJsonDataVeryShort() :String {
    return """{
    "lat":43.2612,
    "lon":23.8347,
    "timezone":"Europe/Sofia"
    """
}

private fun testLocalJsonDataLong() :String {
    return """{
    "lat":43.2612,
    "lon":23.8347,
    "timezone":"Europe/Sofia",
    "timezone_offset":10800,
    "current":{
        "dt":1617121051,
        "sunrise":1617077398,
        "sunset":1617122878,
        "temp":57.2,
        "feels_like":51.57,
        "pressure":1029,
        "humidity":44,
        "dew_point":35.51,
        "uvi":0.14,
        "clouds":20,
        "visibility":10000,
        "wind_speed":4.61,
        "wind_deg":20,
        "weather":[
            {
                "id":801,
                "main":"Clouds",
                "description":"few clouds",
                "icon":"02d"
            }
        ]
    },
    "hourly":[
        {
            "dt":1617120000,
            "temp":57.2,
            "feels_like":51.17,
            "pressure":1029,
            "humidity":44,
            "dew_point":35.51,
            "uvi":0.14,
            "clouds":20,
            "visibility":10000,
            "wind_speed":5.32,
            "wind_deg":76,
            "wind_gust":7.99,
            "weather":[
                {
                    "id":801,
                    "main":"Clouds",
                    "description":"few clouds",
                    "icon":"02d"
                }
            ],
            "pop":0
        },
        {
            "dt":1617123600,
            "temp":53.11,
            "feels_like":47.01,
            "pressure":1029,
            "humidity":51,
            "dew_point":35.49,
            "uvi":0,
            "clouds":24,
            "visibility":10000,
            "wind_speed":5.46,
            "wind_deg":96,
            "wind_gust":5.93,
            "weather":[
                {
                    "id":801,
                    "main":"Clouds",
                    "description":"few clouds",
                    "icon":"02n"
                }
            ],
            "pop":0
        },
        {
            "dt":1617127200,
            "temp":49.42,
            "feels_like":43.83,
            "pressure":1029,
            "humidity":58,
            "dew_point":35.29,
            "uvi":0,
            "clouds":29,
            "visibility":10000,
            "wind_speed":4.5,
            "wind_deg":121,
            "wind_gust":4.47,
            "weather":[
                {
                    "id":802,
                    "main":"Clouds",
                    "description":"scattered clouds",
                    "icon":"03n"
                }
            ],
            "pop":0
        },
        {
            "dt":1617130800,
            "temp":46.87,
            "feels_like":41.59,
            "pressure":1029,
            "humidity":62,
            "dew_point":34.56,
            "uvi":0,
            "clouds":8,
            "visibility":10000,
            "wind_speed":3.71,
            "wind_deg":146,
            "wind_gust":3.74,
            "weather":[
                {
                    "id":800,
                    "main":"Clear",
                    "description":"clear sky",
                    "icon":"01n"
                }
            ],
            "pop":0
        },
        {
            "dt":1617134400,
            "temp":45.52,
            "feels_like":40.46,
            "pressure":1029,
            "humidity":64,
            "dew_point":34.07,
            "uvi":0,
            "clouds":9,
            "visibility":10000,
            "wind_speed":3.18,
            "wind_deg":163,
            "wind_gust":3.15,
            "weather":[
                {
                    "id":800,
                    "main":"Clear",
                    "description":"clear sky",
                    "icon":"01n"
                }
            ],
            "pop":0
        },
        {
            "dt":1617138000,
            "temp":44.71,
            "feels_like":39.99,
            "pressure":1030,
            "humidity":65,
            "dew_point":33.58,
            "uvi":0,
            "clouds":9,
            "visibility":10000,
            "wind_speed":2.48,
            "wind_deg":155,
            "wind_gust":2.75,
            "weather":[
                {
                    "id":800,
                    "main":"Clear",
                    "description":"clear sky",
                    "icon":"01n"
                }
            ],
            "pop":0
        },
        {
            "dt":1617141600,
            "temp":44.19,
            "feels_like":39.45,
            "pressure":1030,
            "humidity":66,
            "dew_point":33.55,
            "uvi":0,
            "clouds":29,
            "visibility":10000,
            "wind_speed":2.48,
            "wind_deg":144,
            "wind_gust":2.77,
            "weather":[
                {
                    "id":802,
                    "main":"Clouds",
                    "description":"scattered clouds",
                    "icon":"03n"
                }
            ],
            "pop":0
        },
        {
            "dt":1617145200,
            "temp":44.28,
            "feels_like":39.56,
            "pressure":1030,
            "humidity":66,
            "dew_point":33.73,
            "uvi":0,
            "clouds":43,
            "visibility":10000,
            "wind_speed":2.48,
            "wind_deg":127,
            "wind_gust":2.77,
            "weather":[
                {
                    "id":802,
                    "main":"Clouds",
                    "description":"scattered clouds",
                    "icon":"03n"
                }
            ],
            "pop":0
        },
        {
            "dt":1617148800,
            "temp":43.75,
            "feels_like":38.3,
            "pressure":1029,
            "humidity":67,
            "dew_point":33.85,
            "uvi":0,
            "clouds":52,
            "visibility":10000,
            "wind_speed":3.76,
            "wind_deg":117,
            "wind_gust":4,
            "weather":[
                {
                    "id":803,
                    "main":"Clouds",
                    "description":"broken clouds",
                    "icon":"04n"
                }
            ],
            "pop":0
        },
        {
            "dt":1617152400,
            "temp":42.24,
            "feels_like":36.46,
            "pressure":1029,
            "humidity":71,
            "dew_point":33.42,
            "uvi":0,
            "clouds":60,
            "visibility":10000,
            "wind_speed":4.32,
            "wind_deg":140,
            "wind_gust":4.65,
            "weather":[
                {
                    "id":803,
                    "main":"Clouds",
                    "description":"broken clouds",
                    "icon":"04n"
                }
            ],
            "pop":0.01
        },
        {
            "dt":1617156000,
            "temp":41.68,
            "feels_like":36.37,
            "pressure":1029,
            "humidity":72,
            "dew_point":33.35,
            "uvi":0,
            "clouds":42,
            "visibility":10000,
            "wind_speed":3.42,
            "wind_deg":180,
            "wind_gust":3.38,
            "weather":[
                {
                    "id":802,
                    "main":"Clouds",
                    "description":"scattered clouds",
                    "icon":"03n"
                }
            ],
            "pop":0
        },
        {
            "dt":1617159600,
            "temp":41.23,
            "feels_like":36.34,
            "pressure":1029,
            "humidity":72,
            "dew_point":33.08,
            "uvi":0,
            "clouds":32,
            "visibility":10000,
            "wind_speed":2.59,
            "wind_deg":199,
            "wind_gust":2.57,
            "weather":[
                {
                    "id":802,
                    "main":"Clouds",
                    "description":"scattered clouds",
                    "icon":"03n"
                }
            ],
            "pop":0
        },
        {
            "dt":1617163200,
            "temp":40.75,
            "feels_like":35.96,
            "pressure":1029,
            "humidity":73,
            "dew_point":32.95,
            "uvi":0,
            "clouds":26,
            "visibility":10000,
            "wind_speed":2.37,
            "wind_deg":174,
            "wind_gust":2.48,
            "weather":[
                {
                    "id":802,
                    "main":"Clouds",
                    "description":"scattered clouds",
                    "icon":"03n"
                }
            ],
            "pop":0
        },
        {
            "dt":1617166800,
            "temp":41.88,
            "feels_like":37.15,
            "pressure":1030,
            "humidity":73,
            "dew_point":34.16,
            "uvi":0.09,
            "clouds":23,
            "visibility":10000,
            "wind_speed":2.57,
            "wind_deg":158,
            "wind_gust":2.48,
            "weather":[
                {
                    "id":801,
                    "main":"Clouds",
                    "description":"few clouds",
                    "icon":"02d"
                }
            ],
            "pop":0
        },
        {
            "dt":1617170400,
            "temp":45.41,
            "feels_like":40.87,
            "pressure":1030,
            "humidity":67,
            "dew_point":35.1,
            "uvi":0.34,
            "clouds":22,
            "visibility":10000,
            "wind_speed":2.55,
            "wind_deg":157,
            "wind_gust":3.47,
            "weather":[
                {
                    "id":801,
                    "main":"Clouds",
                    "description":"few clouds",
                    "icon":"02d"
                }
            ],
            "pop":0
        },
        {
            "dt":1617174000,
            "temp":48.29,
            "feels_like":43.32,
            "pressure":1029,
            "humidity":59,
            "dew_point":34.97,
            "uvi":0.96,
            "clouds":31,
            "visibility":10000,
            "wind_speed":3.2,
            "wind_deg":148,
            "wind_gust":5.1,
            "weather":[
                {
                    "id":802,
                    "main":"Clouds",
                    "description":"scattered clouds",
                    "icon":"03d"
                }
            ],
            "pop":0
        },
        {
            "dt":1617177600,
            "temp":50.14,
            "feels_like":44.26,
            "pressure":1029,
            "humidity":53,
            "dew_point":33.87,
            "uvi":1.67,
            "clouds":33,
            "visibility":10000,
            "wind_speed":4.54,
            "wind_deg":114,
            "wind_gust":6.35,
            "weather":[
                {
                    "id":802,
                    "main":"Clouds",
                    "description":"scattered clouds",
                    "icon":"03d"
                }
            ],
            "pop":0
        },
        {
            "dt":1617181200,
            "temp":51.71,
            "feels_like":45.36,
            "pressure":1029,
            "humidity":51,
            "dew_point":34.39,
            "uvi":2.33,
            "clouds":26,
            "visibility":10000,
            "wind_speed":5.53,
            "wind_deg":93,
            "wind_gust":7.25,
            "weather":[
                {
                    "id":802,
                    "main":"Clouds",
                    "description":"scattered clouds",
                    "icon":"03d"
                }
            ],
            "pop":0
        },
        {
            "dt":1617184800,
            "temp":53.11,
            "feels_like":46.54,
            "pressure":1028,
            "humidity":50,
            "dew_point":35.15,
            "uvi":3.78,
            "clouds":23,
            "visibility":10000,
            "wind_speed":6.13,
            "wind_deg":75,
            "wind_gust":8.05,
            "weather":[
                {
                    "id":801,
                    "main":"Clouds",
                    "description":"few clouds",
                    "icon":"02d"
                }
            ],
            "pop":0
        },
        {
            "dt":1617188400,
            "temp":54.03,
            "feels_like":47.3,
            "pressure":1027,
            "humidity":49,
            "dew_point":35.49,
            "uvi":3.75,
            "clouds":28,
            "visibility":10000,
            "wind_speed":6.51,
            "wind_deg":63,
            "wind_gust":7.99,
            "weather":[
                {
                    "id":802,
                    "main":"Clouds",
                    "description":"scattered clouds",
                    "icon":"03d"
                }
            ],
            "pop":0
        },
        {
            "dt":1617192000,
            "temp":54.95,
            "feels_like":48.18,
            "pressure":1027,
            "humidity":47,
            "dew_point":35.31,
            "uvi":3.14,
            "clouds":32,
            "visibility":10000,
            "wind_speed":6.53,
            "wind_deg":62,
            "wind_gust":7.87,
            "weather":[
                {
                    "id":802,
                    "main":"Clouds",
                    "description":"scattered clouds",
                    "icon":"03d"
                }
            ],
            "pop":0
        },
        {
            "dt":1617195600,
            "temp":55.33,
            "feels_like":48.74,
            "pressure":1026,
            "humidity":45,
            "dew_point":34.86,
            "uvi":2.66,
            "clouds":34,
            "visibility":10000,
            "wind_speed":5.99,
            "wind_deg":61,
            "wind_gust":7.61,
            "weather":[
                {
                    "id":802,
                    "main":"Clouds",
                    "description":"scattered clouds",
                    "icon":"03d"
                }
            ],
            "pop":0
        },
        {
            "dt":1617199200,
            "temp":55.38,
            "feels_like":49.08,
            "pressure":1025,
            "humidity":45,
            "dew_point":34.81,
            "uvi":1.48,
            "clouds":46,
            "visibility":10000,
            "wind_speed":5.48,
            "wind_deg":60,
            "wind_gust":6.87,
            "weather":[
                {
                    "id":802,
                    "main":"Clouds",
                    "description":"scattered clouds",
                    "icon":"03d"
                }
            ],
            "pop":0
        },
        {
            "dt":1617202800,
            "temp":54.66,
            "feels_like":48.27,
            "pressure":1025,
            "humidity":47,
            "dew_point":35.04,
            "uvi":0.6,
            "clouds":50,
            "visibility":10000,
            "wind_speed":5.77,
            "wind_deg":61,
            "wind_gust":6.24,
            "weather":[
                {
                    "id":802,
                    "main":"Clouds",
                    "description":"scattered clouds",
                    "icon":"03d"
                }
            ],
            "pop":0
        },
        {
            "dt":1617206400,
            "temp":52.48,
            "feels_like":46.8,
            "pressure":1025,
            "humidity":58,
            "dew_point":38.39,
            "uvi":0.14,
            "clouds":45,
            "visibility":10000,
            "wind_speed":5.53,
            "wind_deg":76,
            "wind_gust":8.37,
            "weather":[
                {
                    "id":802,
                    "main":"Clouds",
                    "description":"scattered clouds",
                    "icon":"03d"
                }
            ],
            "pop":0
        },
        {
            "dt":1617210000,
            "temp":48.42,
            "feels_like":42.78,
            "pressure":1025,
            "humidity":64,
            "dew_point":37.13,
            "uvi":0,
            "clouds":40,
            "visibility":10000,
            "wind_speed":5.01,
            "wind_deg":102,
            "wind_gust":5.06,
            "weather":[
                {
                    "id":802,
                    "main":"Clouds",
                    "description":"scattered clouds",
                    "icon":"03n"
                }
            ],
            "pop":0
        },
        {
            "dt":1617213600,
            "temp":46.9,
            "feels_like":41.61,
            "pressure":1025,
            "humidity":66,
            "dew_point":36.48,
            "uvi":0,
            "clouds":36,
            "visibility":10000,
            "wind_speed":4.23,
            "wind_deg":136,
            "wind_gust":4.21,
            "weather":[
                {
                    "id":802,
                    "main":"Clouds",
                    "description":"scattered clouds",
                    "icon":"03n"
                }
            ],
            "pop":0
        },
        {
            "dt":1617217200,
            "temp":46.29,
            "feels_like":41.29,
            "pressure":1025,
            "humidity":67,
            "dew_point":36.01,
            "uvi":0,
            "clouds":15,
            "visibility":10000,
            "wind_speed":3.62,
            "wind_deg":184,
            "wind_gust":3.42,
            "weather":[
                {
                    "id":801,
                    "main":"Clouds",
                    "description":"few clouds",
                    "icon":"02n"
                }
            ],
            "pop":0
        },
        {
            "dt":1617220800,
            "temp":45.95,
            "feels_like":40.37,
            "pressure":1024,
            "humidity":67,
            "dew_point":35.65,
            "uvi":0,
            "clouds":33,
            "visibility":10000,
            "wind_speed":4.56,
            "wind_deg":209,
            "wind_gust":4.23,
            "weather":[
                {
                    "id":802,
                    "main":"Clouds",
                    "description":"scattered clouds",
                    "icon":"03n"
                }
            ],
            "pop":0
        },
        {
            "dt":1617224400,
            "temp":47.26,
            "feels_like":41.83,
            "pressure":1023,
            "humidity":64,
            "dew_point":36.12,
            "uvi":0,
            "clouds":53,
            "visibility":10000,
            "wind_speed":4.34,
            "wind_deg":209,
            "wind_gust":4.52,
            "weather":[
                {
                    "id":803,
                    "main":"Clouds",
                    "description":"broken clouds",
                    "icon":"04n"
                }
            ],
            "pop":0
        },
        {
            "dt":1617228000,
            "temp":47.84,
            "feels_like":43.34,
            "pressure":1023,
            "humidity":63,
            "dew_point":36.14,
            "uvi":0,
            "clouds":65,
            "visibility":10000,
            "wind_speed":2.71,
            "wind_deg":181,
            "wind_gust":2.73,
            "weather":[
                {
                    "id":803,
                    "main":"Clouds",
                    "description":"broken clouds",
                    "icon":"04n"
                }
            ],
            "pop":0
        },
        {
            "dt":1617231600,
            "temp":47.66,
            "feels_like":42.62,
            "pressure":1023,
            "humidity":63,
            "dew_point":36.05,
            "uvi":0,
            "clouds":72,
            "visibility":10000,
            "wind_speed":3.62,
            "wind_deg":105,
            "wind_gust":3.53,
            "weather":[
                {
                    "id":803,
                    "main":"Clouds",
                    "description":"broken clouds",
                    "icon":"04n"
                }
            ],
            "pop":0
        },
        {
            "dt":1617235200,
            "temp":47.12,
            "feels_like":41.88,
            "pressure":1023,
            "humidity":66,
            "dew_point":36.32,
            "uvi":0,
            "clouds":76,
            "visibility":10000,
            "wind_speed":4.18,
            "wind_deg":99,
            "wind_gust":4.99,
            "weather":[
                {
                    "id":803,
                    "main":"Clouds",
                    "description":"broken clouds",
                    "icon":"04n"
                }
            ],
            "pop":0
        },
        {
            "dt":1617238800,
            "temp":46.69,
            "feels_like":41.31,
            "pressure":1023,
            "humidity":67,
            "dew_point":36.52,
            "uvi":0,
            "clouds":100,
            "visibility":10000,
            "wind_speed":4.43,
            "wind_deg":110,
            "wind_gust":7.27,
            "weather":[
                {
                    "id":804,
                    "main":"Clouds",
                    "description":"overcast clouds",
                    "icon":"04n"
                }
            ],
            "pop":0.06
        },
        {
            "dt":1617242400,
            "temp":45.28,
            "feels_like":38.75,
            "pressure":1023,
            "humidity":72,
            "dew_point":37.06,
            "uvi":0,
            "clouds":98,
            "visibility":10000,
            "wind_speed":6.6,
            "wind_deg":105,
            "wind_gust":12.01,
            "weather":[
                {
                    "id":804,
                    "main":"Clouds",
                    "description":"overcast clouds",
                    "icon":"04n"
                }
            ],
            "pop":0.09
        },
        {
            "dt":1617246000,
            "temp":44.62,
            "feels_like":36.46,
            "pressure":1023,
            "humidity":79,
            "dew_point":38.5,
            "uvi":0,
            "clouds":98,
            "visibility":10000,
            "wind_speed":10.04,
            "wind_deg":109,
            "wind_gust":16.89,
            "weather":[
                {
                    "id":804,
                    "main":"Clouds",
                    "description":"overcast clouds",
                    "icon":"04n"
                }
            ],
            "pop":0.17
        },
        {
            "dt":1617249600,
            "temp":44.19,
            "feels_like":37.94,
            "pressure":1023,
            "humidity":83,
            "dew_point":39.42,
            "uvi":0,
            "clouds":98,
            "visibility":10000,
            "wind_speed":6.93,
            "wind_deg":139,
            "wind_gust":14.7,
            "weather":[
                {
                    "id":804,
                    "main":"Clouds",
                    "description":"overcast clouds",
                    "icon":"04n"
                }
            ],
            "pop":0.24
        },
        {
            "dt":1617253200,
            "temp":44.82,
            "feels_like":40.32,
            "pressure":1023,
            "humidity":82,
            "dew_point":39.92,
            "uvi":0.19,
            "clouds":98,
            "visibility":10000,
            "wind_speed":3.94,
            "wind_deg":179,
            "wind_gust":7.11,
            "weather":[
                {
                    "id":804,
                    "main":"Clouds",
                    "description":"overcast clouds",
                    "icon":"04d"
                }
            ],
            "pop":0.16
        },
        {
            "dt":1617256800,
            "temp":46.49,
            "feels_like":42.6,
            "pressure":1023,
            "humidity":78,
            "dew_point":40.01,
            "uvi":0.7,
            "clouds":97,
            "visibility":10000,
            "wind_speed":2.98,
            "wind_deg":175,
            "wind_gust":4.59,
            "weather":[
                {
                    "id":804,
                    "main":"Clouds",
                    "description":"overcast clouds",
                    "icon":"04d"
                }
            ],
            "pop":0.16
        },
        {
            "dt":1617260400,
            "temp":49.33,
            "feels_like":44.76,
            "pressure":1023,
            "humidity":66,
            "dew_point":38.57,
            "uvi":1.63,
            "clouds":10,
            "visibility":10000,
            "wind_speed":3.67,
            "wind_deg":134,
            "wind_gust":5.46,
            "weather":[
                {
                    "id":800,
                    "main":"Clear",
                    "description":"clear sky",
                    "icon":"01d"
                }
            ],
            "pop":0
        },
        {
            "dt":1617264000,
            "temp":51.55,
            "feels_like":46.53,
            "pressure":1023,
            "humidity":58,
            "dew_point":37.31,
            "uvi":2.83,
            "clouds":8,
            "visibility":10000,
            "wind_speed":4.07,
            "wind_deg":105,
            "wind_gust":5.73,
            "weather":[
                {
                    "id":800,
                    "main":"Clear",
                    "description":"clear sky",
                    "icon":"01d"
                }
            ],
            "pop":0
        },
        {
            "dt":1617267600,
            "temp":53.24,
            "feels_like":47.93,
            "pressure":1022,
            "humidity":54,
            "dew_point":37.17,
            "uvi":3.94,
            "clouds":7,
            "visibility":10000,
            "wind_speed":4.52,
            "wind_deg":77,
            "wind_gust":5.84,
            "weather":[
                {
                    "id":800,
                    "main":"Clear",
                    "description":"clear sky",
                    "icon":"01d"
                }
            ],
            "pop":0
        },
        {
            "dt":1617271200,
            "temp":54.81,
            "feels_like":48.97,
            "pressure":1022,
            "humidity":51,
            "dew_point":37.11,
            "uvi":4.58,
            "clouds":6,
            "visibility":10000,
            "wind_speed":5.44,
            "wind_deg":65,
            "wind_gust":6.73,
            "weather":[
                {
                    "id":800,
                    "main":"Clear",
                    "description":"clear sky",
                    "icon":"01d"
                }
            ],
            "pop":0
        },
        {
            "dt":1617274800,
            "temp":55.96,
            "feels_like":49.84,
            "pressure":1021,
            "humidity":48,
            "dew_point":36.68,
            "uvi":4.53,
            "clouds":6,
            "visibility":10000,
            "wind_speed":5.82,
            "wind_deg":65,
            "wind_gust":6.33,
            "weather":[
                {
                    "id":800,
                    "main":"Clear",
                    "description":"clear sky",
                    "icon":"01d"
                }
            ],
            "pop":0
        },
        {
            "dt":1617278400,
            "temp":56.91,
            "feels_like":50.68,
            "pressure":1020,
            "humidity":44,
            "dew_point":35.67,
            "uvi":3.81,
            "clouds":6,
            "visibility":10000,
            "wind_speed":5.59,
            "wind_deg":66,
            "wind_gust":5.32,
            "weather":[
                {
                    "id":800,
                    "main":"Clear",
                    "description":"clear sky",
                    "icon":"01d"
                }
            ],
            "pop":0
        },
        {
            "dt":1617282000,
            "temp":57.27,
            "feels_like":51.3,
            "pressure":1020,
            "humidity":42,
            "dew_point":34.88,
            "uvi":2.72,
            "clouds":5,
            "visibility":10000,
            "wind_speed":4.9,
            "wind_deg":73,
            "wind_gust":4.21,
            "weather":[
                {
                    "id":800,
                    "main":"Clear",
                    "description":"clear sky",
                    "icon":"01d"
                }
            ],
            "pop":0
        },
        {
            "dt":1617285600,
            "temp":57.34,
            "feels_like":51.66,
            "pressure":1019,
            "humidity":41,
            "dew_point":34.32,
            "uvi":1.52,
            "clouds":4,
            "visibility":10000,
            "wind_speed":4.25,
            "wind_deg":81,
            "wind_gust":3.24,
            "weather":[
                {
                    "id":800,
                    "main":"Clear",
                    "description":"clear sky",
                    "icon":"01d"
                }
            ],
            "pop":0
        },
        {
            "dt":1617289200,
            "temp":56.91,
            "feels_like":51.6,
            "pressure":1019,
            "humidity":42,
            "dew_point":34.47,
            "uvi":0.62,
            "clouds":4,
            "visibility":10000,
            "wind_speed":3.62,
            "wind_deg":91,
            "wind_gust":2.71,
            "weather":[
                {
                    "id":800,
                    "main":"Clear",
                    "description":"clear sky",
                    "icon":"01d"
                }
            ],
            "pop":0
        }
    ]
}"""
}